# Generated by Django 5.0.4 on 2024-04-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_rename_name_user_displayname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="displayName",
            field=models.CharField(max_length=50),
        ),
    ]
