# Generated by Django 5.0.4 on 2024-04-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="marks",
            field=models.IntegerField(null=True),
        ),
    ]
