# Generated by Django 5.0.4 on 2024-04-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_assignment_marks"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="students",
            field=models.ManyToManyField(
                null=True, related_name="assignments", to="authentication.user"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="link",
            field=models.URLField(null=True),
        ),
    ]
